USE [master]
GO
IF db_id('TrelloClone') IS NULL
    CREATE DATABASE TrelloClone
GO
USE [TrelloClone]
GO
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS [Board];
DROP TABLE IF EXISTS [Card];
DROP TABLE IF EXISTS [Color];
DROP TABLE IF EXISTS [Label];
DROP TABLE IF EXISTS [BoardLabel];
GO 
CREATE TABLE [User] (
  [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
  [UserName] NVARCHAR(50) NOT NULL,
  [Email] NVARCHAR(60) NOT NULL,
  [FirebaseUserId] NVARCHAR(28) NOT NULL,
  CONSTRAINT UQ_FirebaseUserId UNIQUE(FirebaseUserId)
)
CREATE TABLE [Color] (
  [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
  [Name] NVARCHAR(50) NOT NULL,
  [Code] NVARCHAR(30) NOT NULL
)
CREATE TABLE [Label] (
  [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
  [UserId] INTEGER NOT NULL,
  [Name] NVARCHAR(50) NOT NULL,
  CONSTRAINT FK_Label_User FOREIGN KEY (UserId) REFERENCES User(Id),
)
CREATE TABLE [Board] (
  [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
  [UserId] INTEGER NOT NULL,
  [ColorId] INTEGER NOT NULL,
  [Name] NVARCHAR(50) NOT NULL,
  [Description] NVARCHAR(500) NOT NULL,
  CONSTRAINT FK_Board_User FOREIGN KEY (UserId) REFERENCES User(Id),
  CONSTRAINT FK_Board_Color FOREIGN KEY (ColorId) REFERENCES Color(Id)
) 
CREATE TABLE [Card] (
  [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
  [UserId] INTEGER NOT NULL,
  [BoardId] INTEGER NOT NULL,
  [Name] NVARCHAR(50) NOT NULL,
  CONSTRAINT FK_Card_User FOREIGN KEY (UserId) REFERENCES User(Id),
  CONSTRAINT FK_Card_Board FOREIGN KEY (BoardId) REFERENCES Board(Id)
)
CREATE TABLE [BoardLabel] (
  [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
  [UserId] INTEGER NOT NULL,
  [BoardId] INTEGER NOT NULL,
  [LabelId] INTEGER NOT NULL,
  CONSTRAINT FK_BoardLabel_User FOREIGN KEY (UserId) REFERENCES User(Id),
  CONSTRAINT FK_BoardLabel_Board FOREIGN KEY (BoardId) REFERENCES Board(Id),
  CONSTRAINT FK_BoardLabel_Label FOREIGN KEY (LabelId) REFERENCES Label(Id)
)
GO
